In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
my_list=[1,2,3,4,5]

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [7]:
my_mat= [[1,2,3,],[6,7,8],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [6, 7, 8],
       [7, 8, 9]])

In [9]:
range(0,10)

range(0, 10)

In [12]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [26]:
np.random.rand(5)

array([0.25336268, 0.74219676, 0.03287211, 0.72285929, 0.08655229])

In [29]:
np.random.rand(3,5)# 3 raw 5 column

array([[0.50619143, 0.04646405, 0.02942059, 0.62373148, 0.26896617],
       [0.88341328, 0.00489164, 0.72254415, 0.17827534, 0.04470508],
       [0.34040398, 0.5888867 , 0.34829768, 0.26720152, 0.12094055]])

In [30]:
np.random.randn(5)

array([-1.22376767, -0.1006749 , -0.16592861, -0.44940704,  0.65028988])

In [33]:
np.random.randn(3,5)

array([[-0.45488545, -0.40818494, -0.09606365,  1.76783344, -0.25284782],
       [ 0.86260903, -0.33118116, -0.65469849,  1.24957225,  0.20121548],
       [ 0.18368167,  0.8313843 , -1.16839706, -0.17887721,  2.32278812]])

In [34]:
np.random.randint(1,100)

36

In [38]:
np.random.randint(1,100,30) # 1 to 100 30 values with random

array([79, 82, 12, 57, 17, 23, 79, 58, 40, 81, 45, 93, 37, 97, 76,  2, 82,
       43, 99, 83, 33, 34, 69, 45, 34, 61, 57, 37, 38, 81])

In [42]:
arr= np.arange(1,100,2) #start stop, step

In [43]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [44]:
ranarr= np.random.randint(0,50,10)

In [46]:
ranarr

array([36, 26,  9, 40,  2, 45, 42, 45,  8, 21])

In [47]:
ranarr.shape

(10,)

In [49]:
ranarr.reshape(5,2)

array([[36, 26],
       [ 9, 40],
       [ 2, 45],
       [42, 45],
       [ 8, 21]])

In [51]:
arr.shape

(50,)

In [52]:
arr.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [55]:
ranarr.max()

np.int64(45)

In [56]:
ranarr.min()

np.int64(2)

In [58]:
ranarr.argmax() #maximum array index number

np.int64(5)

In [60]:
ranarr.argmin()

np.int64(4)

In [61]:
ranarr

array([36, 26,  9, 40,  2, 45, 42, 45,  8, 21])

In [62]:
type(arr)

numpy.ndarray

In [64]:
arr.dtype

dtype('int64')

- Numpy Array Indexing

In [66]:
arr= np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[8]

np.int64(8)

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [71]:
arr[0:5] = 100

In [72]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [73]:
arr_copy= arr.copy()

In [74]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [75]:
arr_copy[0:5]=500

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [77]:
arr_copy

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

- 2d Array

In [78]:
arr_2d= np.array([[10,20,30],[40,50,60],[70,80,90]])

In [79]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [81]:
arr_2d[0][1] #raw x column

np.int64(20)

In [82]:
arr_2d[1] # 2nd Row

array([40, 50, 60])

In [84]:
arr_2d[0] #1st row

array([10, 20, 30])

In [86]:
arr_2d[1][2]

np.int64(60)

In [87]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [89]:
arr_2d[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [90]:
arr_2d[1:2]

array([[40, 50, 60]])

In [91]:
arr_2d[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [93]:
arr_2d[:2,:1]

array([[10],
       [40]])

In [94]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [95]:
arr_2d[1:,:2]

array([[40, 50],
       [70, 80]])

In [98]:
arr2=np.arange(0,10)

In [99]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr2>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [101]:
arr2[arr2>5]

array([6, 7, 8, 9])

In [102]:
arr_2d= np.arange(50).reshape()

AttributeError: module 'numpy' has no attribute 'aranage'